/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 --transform --types --exportdefault cutting_mat.glb 
Files: cutting_mat.glb [2.09MB] > /Users/adam/Desktop/adamturaj.com/public/models/cutting_mat-transformed.glb [57.15KB] (97%)
Author: shpawen (https://sketchfab.com/shpawen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/voxel-cutting-mat-85e51c02c3a747ee8394a9a6f163dec7
Title: Voxel Cutting Mat
*/

import * as THREE from "three";

import React from "react";

import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh;
  };
  materials: {
    ["palette.016"]: THREE.MeshBasicMaterial;
  };
};

const CuttingMat = (props: JSX.IntrinsicElements["group"]) => {
  const { nodes, materials } = useGLTF("/models/cuttingMat.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials["palette.016"]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        position={[0.2, -0.028, -0.3]}
        scale={0.03}
      />
    </group>
  );
};

useGLTF.preload("/models/cuttingMat.glb");

export default CuttingMat;
