/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 Kicad.gltf --transform --types 
Files: Kicad.gltf [5.31MB] > /Users/adam/Desktop/gltf/Kicad-transformed.glb [1.04MB] (80%)
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Body1: THREE.Mesh;
    Body1_1: THREE.Mesh;
    Body1_2: THREE.Mesh;
    Body1_3: THREE.Mesh;
    Body1_4: THREE.Mesh;
    Body1_5: THREE.Mesh;
    Body1_6: THREE.Mesh;
  };
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial;
    PaletteMaterial002: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

const PCBModel = (props: JSX.IntrinsicElements["group"]) => {
  const { nodes, materials } = useGLTF("/Kicad-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Body1.geometry}
        material={materials.PaletteMaterial001}
        position={[0.159, -0.1, 0.002]}
        rotation={[0, 0, Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Body1_1.geometry}
        material={materials.PaletteMaterial002}
        position={[0.15, -0.109, 0.002]}
        rotation={[Math.PI / 2, Math.PI / 2, 0]}
      />
      <instancedMesh
        args={[nodes.Body1_2.geometry, materials.PaletteMaterial001, 40]}
        instanceMatrix={nodes.Body1_2.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Body1_3.geometry, materials.PaletteMaterial001, 40]}
        instanceMatrix={nodes.Body1_3.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Body1_4.geometry, materials.PaletteMaterial001, 10]}
        instanceMatrix={nodes.Body1_4.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Body1_5.geometry, materials.PaletteMaterial001, 10]}
        instanceMatrix={nodes.Body1_5.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Body1_6.geometry, materials.PaletteMaterial001, 10]}
        instanceMatrix={nodes.Body1_6.instanceMatrix}
      />
    </group>
  );
};

useGLTF.preload("/Kicad-transformed.glb");

export default PCBModel;
