/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 output2.glb --types --exportdefault --precision 6 
*/

import * as THREE from "three";

import { Plane, useGLTF, useTexture, useVideoTexture } from "@react-three/drei";
import { GLTF } from "three-stdlib";

import CuttingMat from "./CuttingMat";

type GLTFResult = GLTF & {
  nodes: {
    cavo005: THREE.Mesh;
    Cube266: THREE.Mesh;
    Cube266_1: THREE.Mesh;
    Cube266_2: THREE.Mesh;
    Cube266_3: THREE.Mesh;
    Body1209: THREE.Mesh;
    Body10006: THREE.Mesh;
    Body100004: THREE.Mesh;
    Body184002: THREE.Mesh;
    Body186002: THREE.Mesh;
    Body5006: THREE.Mesh;
    Body67005: THREE.Mesh;
    Body1003: THREE.Mesh;
    Body1006: THREE.Mesh;
    Body1004: THREE.Mesh;
    Body1: THREE.Mesh;
    Body1007: THREE.Mesh;
    Body1007_1: THREE.Mesh;
    Body1064: THREE.Mesh;
    Body1064_1: THREE.Mesh;
    Body1203: THREE.Mesh;
    Body1158: THREE.Mesh;
    Body1172: THREE.Mesh;
    Body1149: THREE.Mesh;
    Body1038: THREE.Mesh;
    Body1039: THREE.Mesh;
    Body1130: THREE.Mesh;
    Body1049: THREE.Mesh;
    Body1050: THREE.Mesh;
    Body1051: THREE.Mesh;
    Body1100: THREE.Mesh;
    Body1019: THREE.Mesh;
    Body1011: THREE.Mesh;
    Back_handle: THREE.Mesh;
    ["Buton-Blue"]: THREE.Mesh;
    Cube015: THREE.Mesh;
    Cube015_1: THREE.Mesh;
    Cube015_2: THREE.Mesh;
    ["BUTON-RUN-STOP"]: THREE.Mesh;
    Cube012: THREE.Mesh;
    Cube012_1: THREE.Mesh;
    Button_arrow001: THREE.Mesh;
    Buttons_on_the_right: THREE.Mesh;
    Screen002: THREE.Mesh;
    Screen002_1: THREE.Mesh;
    Screen002_2: THREE.Mesh;
    Screen002_3: THREE.Mesh;
    Screen002_4: THREE.Mesh;
    Screen002_5: THREE.Mesh;
    ["Device_name_-_heading"]: THREE.Mesh;
    Cube013: THREE.Mesh;
    Cube013_1: THREE.Mesh;
    internal_screen: THREE.Mesh;
    ["Knop-Big001"]: THREE.Mesh;
    Cube002: THREE.Mesh;
    Cube002_1: THREE.Mesh;
    Cube002_2: THREE.Mesh;
    Cube002_3: THREE.Mesh;
    Cube002_4: THREE.Mesh;
    ["3220476_original_(1)-edit2009"]: THREE.Mesh;
    ["3220476_original_(1)-edit2009_1"]: THREE.Mesh;
    Rear_text: THREE.Mesh;
    Screen_1: THREE.Mesh;
    Screen_2: THREE.Mesh;
    Screen001: THREE.Mesh;
    Shielding_plate_inside: THREE.Mesh;
    TXT_USB_Host_etc: THREE.Mesh;
    TXT_serial_nr: THREE.Mesh;
    VGA: THREE.Mesh;
    Cylinder011: THREE.Mesh;
    Cylinder011_1: THREE.Mesh;
    Cylinder011_2: THREE.Mesh;
    attacco_cavo001: THREE.Mesh;
    connector_usbc002: THREE.Mesh;
  };
  materials: {
    ["Computer Screen"]: THREE.MeshStandardMaterial;
    Arbetshylla: THREE.MeshStandardMaterial;
    ["Arbetsbänk Skiva"]: THREE.MeshStandardMaterial;
    ["Leg.001"]: THREE.MeshStandardMaterial;
    ["Mat 01"]: THREE.MeshStandardMaterial;
    ["Opaque(244,244,244)"]: THREE.MeshStandardMaterial;
    ["Opaque(5,5,5)"]: THREE.MeshStandardMaterial;
    ["Opaque(191,191,191)"]: THREE.MeshStandardMaterial;
    ["Opaque(63,63,63)"]: THREE.MeshStandardMaterial;
    ["Opaque(173,173,173)"]: THREE.MeshStandardMaterial;
    ["Opaque(190,188,186)"]: THREE.MeshStandardMaterial;
    ["Opaque(128,128,128)"]: THREE.MeshStandardMaterial;
    ["Opaque(219,188,126)"]: THREE.MeshStandardMaterial;
    ["Opaque(250,235,214)"]: THREE.MeshStandardMaterial;
    ["Opaque(65,195,130)"]: THREE.MeshStandardMaterial;
    ["Opaque(51,153,102)"]: THREE.MeshStandardMaterial;
    ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
    ["Opaque(97,69,55)"]: THREE.MeshStandardMaterial;
    ["Opaque(228,227,207)"]: THREE.MeshStandardMaterial;
    ["Opaque(21,22,24)"]: THREE.MeshStandardMaterial;
    ["Opaque(204,204,204)"]: THREE.MeshStandardMaterial;
    ["Opaque(87,173,113)"]: THREE.MeshStandardMaterial;
    ["Opaque(70,70,70)"]: THREE.MeshStandardMaterial;
    ["Opaque(38,37,37)"]: THREE.MeshStandardMaterial;
    ["Opaque(255,255,255)"]: THREE.MeshStandardMaterial;
    ["Opaque(247,224,153)"]: THREE.MeshStandardMaterial;
    ["Opaque(255,245,209)"]: THREE.MeshStandardMaterial;
    ["Opaque(150,150,150)"]: THREE.MeshStandardMaterial;
    ["Opaque(50,50,50)"]: THREE.MeshStandardMaterial;
    ["Opaque(185,185,185)"]: THREE.MeshStandardMaterial;
    ["Opaque(37,36,36)"]: THREE.MeshStandardMaterial;
    ["Opaque(176,169,152)"]: THREE.MeshStandardMaterial;
    ["Opaque(41,41,41)"]: THREE.MeshStandardMaterial;
    ["Plastic structured in gray"]: THREE.MeshStandardMaterial;
    ["Buton-Blau"]: THREE.MeshStandardMaterial;
    Grau: THREE.MeshStandardMaterial;
    ["LED-Grün"]: THREE.MeshStandardMaterial;
    ["Besch.Tasten-hintergrund"]: THREE.MeshStandardMaterial;
    ["RUN-STOP_txt"]: THREE.MeshStandardMaterial;
    ["Menue-buton-M"]: THREE.MeshStandardMaterial;
    ["Menue-buton.Color"]: THREE.MeshStandardMaterial;
    ["Menue-Pfeile-blau"]: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    Restauration: THREE.MeshStandardMaterial;
    ["Metal-Farbe-01"]: THREE.MeshStandardMaterial;
    Besch: THREE.MeshStandardMaterial;
    Metal: THREE.MeshStandardMaterial;
    Isolator: THREE.MeshStandardMaterial;
    Kupfer: THREE.MeshStandardMaterial;
    ["Besch.Überschrift"]: THREE.MeshStandardMaterial;
    ["Kabel-Schwarz"]: THREE.MeshStandardMaterial;
    ["Kabel-Metal"]: THREE.MeshStandardMaterial;
    Black: THREE.MeshStandardMaterial;
    Knop: THREE.MeshStandardMaterial;
    LED_Grün: THREE.MeshStandardMaterial;
    LED_Rot: THREE.MeshStandardMaterial;
    Stecker_Schwarz: THREE.MeshStandardMaterial;
    ["Steel_Gebürsted.004"]: THREE.MeshStandardMaterial;
    ["Gold.002"]: THREE.MeshStandardMaterial;
    Schwarz_01: THREE.MeshStandardMaterial;
    ["Gold.Steel.002"]: THREE.MeshStandardMaterial;
    Text_hinten: THREE.MeshStandardMaterial;
    Screen: THREE.MeshStandardMaterial;
    Platine: THREE.MeshStandardMaterial;
    Glas: THREE.MeshPhysicalMaterial;
    ["Car chrome"]: THREE.MeshStandardMaterial;
    ["Beschriftung hinten-USB"]: THREE.MeshStandardMaterial;
    ["TXT_Hinten-die-zweite"]: THREE.MeshStandardMaterial;
    ["Gray black pastic"]: THREE.MeshStandardMaterial;
    ["Metal.003"]: THREE.MeshStandardMaterial;
    ["Kabel-Schwarz.004"]: THREE.MeshStandardMaterial;
    ["Gold.005"]: THREE.MeshStandardMaterial;
    ["black grain.004"]: THREE.MeshStandardMaterial;
    ["metal_02.005"]: THREE.MeshStandardMaterial;
  };
};

const Scene = (props: JSX.IntrinsicElements["group"]) => {
  const { nodes, materials } = useGLTF(
    "/models/PortfolioScene.glb"
  ) as GLTFResult;
  const screenVideoTexture = useVideoTexture("/textures/computerScreen.mp4");
  const oscilloscopeTexture = useTexture("textures/OscilloscopeScreen.jpg");

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.cavo005.geometry}
        material={materials["Computer Screen"]}
        position={[0.087322, -0.015202, -0.000158]}
      />
      <Plane
        args={[0.3, 0.18]}
        position={[0.11, 0.089, -0.301]}
        rotation={[
          (-32.5 * Math.PI) / 180,
          -Math.PI / 3.58,
          (-26.5 * Math.PI) / 180,
        ]}
      >
        <meshBasicMaterial map={screenVideoTexture} toneMapped={false} />
      </Plane>
      <group
        position={[0.087322, -0.015202, -0.000158]}
        scale={[0.145156, 0.01, 0.92]}
      >
        <mesh
          geometry={nodes.Cube266.geometry}
          material={materials.Arbetshylla}
        />
        <mesh
          geometry={nodes.Cube266_1.geometry}
          material={materials["Arbetsbänk Skiva"]}
        />
        <mesh
          geometry={nodes.Cube266_2.geometry}
          material={materials["Leg.001"]}
        />
        <mesh
          geometry={nodes.Cube266_3.geometry}
          material={materials["Mat 01"]}
        />
      </group>
      <mesh
        geometry={nodes.Body1209.geometry}
        material={materials["Opaque(244,244,244)"]}
        position={[0.087322, -0.015202, -0.000158]}
      />
      <mesh
        geometry={nodes.Body10006.geometry}
        material={materials["Opaque(5,5,5)"]}
        position={[0.087322, -0.015202, -0.000158]}
      />
      <mesh
        geometry={nodes.Body100004.geometry}
        material={materials["Opaque(191,191,191)"]}
        position={[0.087322, -0.015202, -0.000158]}
      />
      <mesh
        geometry={nodes.Body184002.geometry}
        material={materials["Opaque(63,63,63)"]}
        position={[0.087322, -0.015202, -0.000158]}
      />
      <mesh
        geometry={nodes.Body186002.geometry}
        material={materials["Opaque(173,173,173)"]}
        position={[0.087322, -0.015202, -0.000158]}
      />
      <mesh
        geometry={nodes.Body5006.geometry}
        material={materials["Opaque(190,188,186)"]}
        position={[0.087322, -0.015202, -0.000158]}
      />
      <mesh
        geometry={nodes.Body67005.geometry}
        material={materials["Opaque(128,128,128)"]}
        position={[0.087322, -0.015202, -0.000158]}
      />
      <mesh
        geometry={nodes.Body1003.geometry}
        material={materials["Opaque(219,188,126)"]}
        position={[0.087322, -0.015202, -0.000158]}
      />
      <mesh
        geometry={nodes.Body1006.geometry}
        material={materials["Opaque(250,235,214)"]}
        position={[0.087322, -0.015202, -0.000158]}
      />
      <mesh
        geometry={nodes.Body1004.geometry}
        material={materials["Opaque(65,195,130)"]}
        position={[0.087322, -0.015202, -0.000158]}
      />
      <mesh
        geometry={nodes.Body1.geometry}
        material={materials["Opaque(51,153,102)"]}
        position={[0.087322, -0.015202, -0.000158]}
      />
      <group
        position={[-0.007949, 0.017236, 0.242663]}
        rotation={[-1.399931, 0.770509, -1.813642]}
        scale={0.02}
      >
        <mesh
          geometry={nodes.Body1007.geometry}
          material={materials["Opaque(210,209,199)"]}
        />
        <mesh
          geometry={nodes.Body1007_1.geometry}
          material={materials["Opaque(97,69,55)"]}
        />
      </group>
      <group
        position={[-0.030291, -0.004194, 0.246014]}
        rotation={[1.741661, -0.77051, -1.327951]}
        scale={0.02}
      >
        <mesh
          geometry={nodes.Body1064.geometry}
          material={materials["Opaque(228,227,207)"]}
        />
        <mesh
          geometry={nodes.Body1064_1.geometry}
          material={materials["Opaque(21,22,24)"]}
        />
      </group>
      <mesh
        geometry={nodes.Body1203.geometry}
        material={materials["Opaque(204,204,204)"]}
        position={[-0.022596, 0.003663, 0.247614]}
        rotation={[-1.741661, -0.77051, 2.898747]}
        scale={0.02}
      />
      <mesh
        geometry={nodes.Body1158.geometry}
        material={materials["Opaque(87,173,113)"]}
        position={[-0.002781, 0.014842, 0.172913]}
        rotation={[Math.PI, 0.173415, 2.356194]}
        scale={0.02}
      />
      <mesh
        geometry={nodes.Body1172.geometry}
        material={materials["Opaque(70,70,70)"]}
        position={[-0.019232, -0.001682, 0.171062]}
        rotation={[Math.PI, 0.173415, 2.356194]}
        scale={0.02}
      />
      <mesh
        geometry={nodes.Body1149.geometry}
        material={materials["Opaque(38,37,37)"]}
        position={[-0.037706, -0.008147, 0.239048]}
        rotation={[-1.399931, 0.770509, 1.327951]}
        scale={0.02}
      />
      <mesh
        geometry={nodes.Body1038.geometry}
        material={materials["Opaque(255,255,255)"]}
        position={[-0.04203, -0.021079, 0.188786]}
        rotation={[1.399931, 0.77051, -1.327951]}
        scale={0.02}
      />
      <mesh
        geometry={nodes.Body1039.geometry}
        material={materials["Opaque(247,224,153)"]}
        position={[-0.04203, -0.021079, 0.188786]}
        rotation={[1.399931, 0.77051, -1.327951]}
        scale={0.02}
      />
      <mesh
        geometry={nodes.Body1130.geometry}
        material={materials["Opaque(255,245,209)"]}
        position={[0.007748, 0.035291, 0.206733]}
        rotation={[1.399931, 0.77051, -1.327951]}
        scale={0.02}
      />
      <mesh
        geometry={nodes.Body1049.geometry}
        material={materials["Opaque(150,150,150)"]}
        position={[-0.02851, -0.001918, 0.222655]}
        rotation={[0, -0.173415, Math.PI / 4]}
        scale={0.02}
      />
      <mesh
        geometry={nodes.Body1050.geometry}
        material={materials["Opaque(50,50,50)"]}
        position={[-0.02851, -0.001918, 0.222655]}
        rotation={[0, -0.173415, Math.PI / 4]}
        scale={0.02}
      />
      <mesh
        geometry={nodes.Body1051.geometry}
        material={materials["Opaque(185,185,185)"]}
        position={[-0.02851, -0.001918, 0.222655]}
        rotation={[0, -0.173415, Math.PI / 4]}
        scale={0.02}
      />
      <mesh
        geometry={nodes.Body1100.geometry}
        material={materials["Opaque(37,36,36)"]}
        position={[-0.016376, 0.004066, 0.188066]}
        rotation={[0, -0.173415, Math.PI / 4]}
        scale={0.02}
      />
      <mesh
        geometry={nodes.Body1019.geometry}
        material={materials["Opaque(176,169,152)"]}
        position={[0.002282, 0.029333, 0.227993]}
        rotation={[-1.399931, 0.770509, 1.327951]}
        scale={0.02}
      />
      <mesh
        geometry={nodes.Body1011.geometry}
        material={materials["Opaque(41,41,41)"]}
        position={[-0.025366, -0.001081, 0.209561]}
        rotation={[Math.PI, 0.173415, 2.356194]}
        scale={0.02}
      />
      <mesh
        geometry={nodes.Back_handle.geometry}
        material={materials["Plastic structured in gray"]}
        position={[0.087322, -0.015202, -0.000158]}
      />
      <mesh
        geometry={nodes["Buton-Blue"].geometry}
        material={materials["Buton-Blau"]}
        position={[0.087322, -0.015202, -0.000158]}
      />
      <group position={[0.087322, -0.015202, -0.000158]}>
        <mesh geometry={nodes.Cube015.geometry} material={materials.Grau} />
        <mesh
          geometry={nodes.Cube015_1.geometry}
          material={materials["LED-Grün"]}
        />
        <mesh
          geometry={nodes.Cube015_2.geometry}
          material={materials["Besch.Tasten-hintergrund"]}
        />
      </group>
      <mesh
        geometry={nodes["BUTON-RUN-STOP"].geometry}
        material={materials["RUN-STOP_txt"]}
        position={[0.087322, -0.015202, -0.000158]}
      />
      <group position={[0.087322, -0.015202, -0.000158]}>
        <mesh
          geometry={nodes.Cube012.geometry}
          material={materials["Menue-buton-M"]}
        />
        <mesh
          geometry={nodes.Cube012_1.geometry}
          material={materials["Menue-buton.Color"]}
        />
      </group>
      <mesh
        geometry={nodes.Button_arrow001.geometry}
        material={materials["Menue-Pfeile-blau"]}
        position={[0.087322, -0.015202, -0.000158]}
      />
      <mesh
        geometry={nodes.Buttons_on_the_right.geometry}
        material={materials["Material.001"]}
        position={[0.087322, -0.015202, -0.000158]}
      />
      <group position={[0.087322, -0.015202, -0.000158]}>
        <mesh
          geometry={nodes.Screen002.geometry}
          material={materials.Restauration}
        />
        <mesh
          geometry={nodes.Screen002_1.geometry}
          material={materials["Metal-Farbe-01"]}
        />
        <mesh
          geometry={nodes.Screen002_2.geometry}
          material={materials.Besch}
        />
        <mesh
          geometry={nodes.Screen002_3.geometry}
          material={materials.Metal}
        />
        <mesh
          geometry={nodes.Screen002_4.geometry}
          material={materials.Isolator}
        />
        <mesh
          geometry={nodes.Screen002_5.geometry}
          material={materials.Kupfer}
        />
      </group>
      <mesh
        geometry={nodes["Device_name_-_heading"].geometry}
        material={materials["Besch.Überschrift"]}
        position={[0.087322, -0.015202, -0.000158]}
      />
      <group position={[0.087322, -0.015202, -0.000158]}>
        <mesh
          geometry={nodes.Cube013.geometry}
          material={materials["Kabel-Schwarz"]}
        />
        <mesh
          geometry={nodes.Cube013_1.geometry}
          material={materials["Kabel-Metal"]}
        />
      </group>
      <mesh
        geometry={nodes.internal_screen.geometry}
        material={materials.Black}
        position={[0.087322, -0.015202, -0.000158]}
      />
      <mesh
        geometry={nodes["Knop-Big001"].geometry}
        material={materials.Knop}
        position={[0.087322, -0.015202, -0.000158]}
      />
      <group position={[0.087322, -0.015202, -0.000158]}>
        <mesh geometry={nodes.Cube002.geometry} material={materials.LED_Grün} />
        <mesh
          geometry={nodes.Cube002_1.geometry}
          material={materials.LED_Rot}
        />
        <mesh
          geometry={nodes.Cube002_2.geometry}
          material={materials.Stecker_Schwarz}
        />
        <mesh
          geometry={nodes.Cube002_3.geometry}
          material={materials["Steel_Gebürsted.004"]}
        />
        <mesh
          geometry={nodes.Cube002_4.geometry}
          material={materials["Gold.002"]}
        />
      </group>
      <group position={[0.087322, -0.015202, -0.000158]}>
        <mesh
          geometry={nodes["3220476_original_(1)-edit2009"].geometry}
          material={materials.Schwarz_01}
        />
        <mesh
          geometry={nodes["3220476_original_(1)-edit2009_1"].geometry}
          material={materials["Gold.Steel.002"]}
        />
      </group>
      <mesh
        geometry={nodes.Rear_text.geometry}
        material={materials.Text_hinten}
        position={[0.087322, -0.015202, -0.000158]}
      />
      <group position={[0.087322, -0.015202, -0.000158]}>
        <mesh geometry={nodes.Screen_1.geometry}>
          <meshStandardMaterial map={oscilloscopeTexture} toneMapped={false} />
        </mesh>
        <mesh geometry={nodes.Screen_2.geometry} material={materials.Platine} />
      </group>
      <mesh
        geometry={nodes.Screen001.geometry}
        material={materials.Glas}
        position={[0.087322, -0.015202, -0.000158]}
      />
      <mesh
        geometry={nodes.Shielding_plate_inside.geometry}
        material={materials["Car chrome"]}
        position={[0.087322, -0.015202, -0.000158]}
      />
      <mesh
        geometry={nodes.TXT_USB_Host_etc.geometry}
        material={materials["Beschriftung hinten-USB"]}
        position={[0.087322, -0.015202, -0.000158]}
      />
      <mesh
        geometry={nodes.TXT_serial_nr.geometry}
        material={materials["TXT_Hinten-die-zweite"]}
        position={[0.087322, -0.015202, -0.000158]}
      />
      <mesh
        geometry={nodes.VGA.geometry}
        material={materials["Gray black pastic"]}
        position={[0.087322, -0.015202, -0.000158]}
      />
      <group position={[0.087322, -0.015202, -0.000158]}>
        <mesh
          geometry={nodes.Cylinder011.geometry}
          material={materials["Metal.003"]}
        />
        <mesh
          geometry={nodes.Cylinder011_1.geometry}
          material={materials["Kabel-Schwarz.004"]}
        />
        <mesh
          geometry={nodes.Cylinder011_2.geometry}
          material={materials["Gold.005"]}
        />
      </group>
      <mesh
        geometry={nodes.attacco_cavo001.geometry}
        material={materials["black grain.004"]}
        position={[0.164812, -0.017582, -0.092719]}
        rotation={[0, -0.958814, 0]}
        scale={[0.073927, 0.126303, 0.122588]}
      />
      <mesh
        geometry={nodes.connector_usbc002.geometry}
        material={materials["metal_02.005"]}
        position={[0.140251, -0.017582, -0.127713]}
        rotation={[-Math.PI, -0.611982, -Math.PI]}
        scale={[0.147105, 0.151564, 0.147854]}
      />
      <CuttingMat />
    </group>
  );
};

useGLTF.preload("/models/PortfolioScene.glb");

export default Scene;
