/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 PortfolioScene.glb --types 
*/

import * as THREE from "three";
import React from "react";
import { Plane, useGLTF, useVideoTexture } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Computer_1: THREE.Mesh;
    Computer_2: THREE.Mesh;
    Computer_3: THREE.Mesh;
    Computer_4: THREE.Mesh;
    Computer_5: THREE.Mesh;
    Computer_6: THREE.Mesh;
    Computer_7: THREE.Mesh;
    Computer_8: THREE.Mesh;
    PCB_Model_1: THREE.Mesh;
    PCB_Model_2: THREE.Mesh;
    PCB_Model_3: THREE.Mesh;
    PCB_Model_4: THREE.Mesh;
    PCB_Model_5: THREE.Mesh;
    PCB_Model_6: THREE.Mesh;
    PCB_Model_7: THREE.Mesh;
    PCB_Model_8: THREE.Mesh;
    PCB_Model_9: THREE.Mesh;
    PCB_Model_10: THREE.Mesh;
    PCB_Model_11: THREE.Mesh;
    PCB_Model_12: THREE.Mesh;
    PCB_Model_13: THREE.Mesh;
    PCB_Model_14: THREE.Mesh;
    PCB_Model_15: THREE.Mesh;
    PCB_Model_16: THREE.Mesh;
    PCB_Model_17: THREE.Mesh;
    PCB_Model_18: THREE.Mesh;
    PCB_Model_19: THREE.Mesh;
    PCB_Model_20: THREE.Mesh;
    PCB_Model_21: THREE.Mesh;
    Bench_1: THREE.Mesh;
    Bench_2: THREE.Mesh;
    Bench_3: THREE.Mesh;
    Bench_4: THREE.Mesh;
    USB_Cable: THREE.Mesh;
    USB_Heads_1: THREE.Mesh;
    USB_Heads_2: THREE.Mesh;
    USB_Heads_3: THREE.Mesh;
    Oscilloscope_1: THREE.Mesh;
    Oscilloscope_2: THREE.Mesh;
    Oscilloscope_3: THREE.Mesh;
    Oscilloscope_4: THREE.Mesh;
    Oscilloscope_5: THREE.Mesh;
    Oscilloscope_6: THREE.Mesh;
    Oscilloscope_7: THREE.Mesh;
    Oscilloscope_8: THREE.Mesh;
    Oscilloscope_9: THREE.Mesh;
    Oscilloscope_10: THREE.Mesh;
    Oscilloscope_11: THREE.Mesh;
    Oscilloscope_12: THREE.Mesh;
    Oscilloscope_13: THREE.Mesh;
    Oscilloscope_14: THREE.Mesh;
    Oscilloscope_15: THREE.Mesh;
    Oscilloscope_16: THREE.Mesh;
    Oscilloscope_17: THREE.Mesh;
    Oscilloscope_18: THREE.Mesh;
    Oscilloscope_19: THREE.Mesh;
    Oscilloscope_20: THREE.Mesh;
    Oscilloscope_21: THREE.Mesh;
    Oscilloscope_22: THREE.Mesh;
    Oscilloscope_23: THREE.Mesh;
    Oscilloscope_24: THREE.Mesh;
    Oscilloscope_25: THREE.Mesh;
    Oscilloscope_26: THREE.Mesh;
    Oscilloscope_27: THREE.Mesh;
    Oscilloscope_28: THREE.Mesh;
    Oscilloscope_29: THREE.Mesh;
    Oscilloscope_30: THREE.Mesh;
    Oscilloscope_31: THREE.Mesh;
    Oscilloscope_32: THREE.Mesh;
    Oscilloscope_33: THREE.Mesh;
    Oscilloscope_34: THREE.Mesh;
    Oscilloscope_35: THREE.Mesh;
    Oscilloscope_36: THREE.Mesh;
    Oscilloscope_37: THREE.Mesh;
    Oscilloscope_38: THREE.Mesh;
    Oscilloscope_39: THREE.Mesh;
    Oscilloscope_40: THREE.Mesh;
    Oscilloscope_41: THREE.Mesh;
    Oscilloscope_42: THREE.Mesh;
    Oscilloscope_43: THREE.Mesh;
    Oscilloscope_44: THREE.Mesh;
    Oscilloscope_45: THREE.Mesh;
    Oscilloscope_46: THREE.Mesh;
    Oscilloscope_47: THREE.Mesh;
    Oscilloscope_48: THREE.Mesh;
    Oscilloscope_49: THREE.Mesh;
    Oscilloscope_50: THREE.Mesh;
    Oscilloscope_51: THREE.Mesh;
    Oscilloscope_52: THREE.Mesh;
    Oscilloscope_53: THREE.Mesh;
    Oscilloscope_54: THREE.Mesh;
    Oscilloscope_55: THREE.Mesh;
    Oscilloscope_56: THREE.Mesh;
    Probe_Cable: THREE.Mesh;
  };
  materials: {
    ["Opaque(244,244,244)"]: THREE.MeshStandardMaterial;
    ["Opaque(5,5,5)"]: THREE.MeshStandardMaterial;
    ["Opaque(190,188,186)"]: THREE.MeshStandardMaterial;
    ["Opaque(128,128,128)"]: THREE.MeshStandardMaterial;
    ["Opaque(191,191,191)"]: THREE.MeshStandardMaterial;
    ["Opaque(63,63,63)"]: THREE.MeshStandardMaterial;
    ["Opaque(173,173,173)"]: THREE.MeshStandardMaterial;
    ["Opaque(204,204,204)"]: THREE.MeshStandardMaterial;
    ["Opaque(219,188,126)"]: THREE.MeshStandardMaterial;
    ["Opaque(250,235,214)"]: THREE.MeshStandardMaterial;
    ["Opaque(65,195,130)"]: THREE.MeshStandardMaterial;
    ["Opaque(51,153,102)"]: THREE.MeshStandardMaterial;
    ["Opaque(210,209,199)"]: THREE.MeshStandardMaterial;
    ["Opaque(97,69,55)"]: THREE.MeshStandardMaterial;
    ["Opaque(228,227,207)"]: THREE.MeshStandardMaterial;
    ["Opaque(21,22,24)"]: THREE.MeshStandardMaterial;
    ["Opaque(87,173,113)"]: THREE.MeshStandardMaterial;
    ["Opaque(70,70,70)"]: THREE.MeshStandardMaterial;
    ["Opaque(38,37,37)"]: THREE.MeshStandardMaterial;
    ["Opaque(255,255,255)"]: THREE.MeshStandardMaterial;
    ["Opaque(247,224,153)"]: THREE.MeshStandardMaterial;
    ["Opaque(255,245,209)"]: THREE.MeshStandardMaterial;
    ["Opaque(150,150,150)"]: THREE.MeshStandardMaterial;
    ["Opaque(50,50,50)"]: THREE.MeshStandardMaterial;
    ["Opaque(185,185,185)"]: THREE.MeshStandardMaterial;
    ["Opaque(37,36,36)"]: THREE.MeshStandardMaterial;
    ["Opaque(176,169,152)"]: THREE.MeshStandardMaterial;
    ["Opaque(41,41,41)"]: THREE.MeshStandardMaterial;
    Arbetshylla: THREE.MeshStandardMaterial;
    ["Arbetsbänk Skiva"]: THREE.MeshStandardMaterial;
    ["Leg.001"]: THREE.MeshStandardMaterial;
    ["Mat 01"]: THREE.MeshStandardMaterial;
    ["black.004"]: THREE.MeshStandardMaterial;
    ["black grain.004"]: THREE.MeshStandardMaterial;
    ["metal_02.005"]: THREE.MeshStandardMaterial;
    ["Plastic structured in gray"]: THREE.MeshStandardMaterial;
    ["Menue-buton-M"]: THREE.MeshStandardMaterial;
    ["Menue-buton.Color"]: THREE.MeshStandardMaterial;
    ["Buton-Blau"]: THREE.MeshStandardMaterial;
    ["Besch.Tasten-hintergrund"]: THREE.MeshStandardMaterial;
    Grau: THREE.MeshStandardMaterial;
    ["LED-Grün"]: THREE.MeshStandardMaterial;
    ["RUN-STOP_txt"]: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    Besch: THREE.MeshStandardMaterial;
    ["Metal-Farbe-01"]: THREE.MeshStandardMaterial;
    Metal: THREE.MeshStandardMaterial;
    Isolator: THREE.MeshStandardMaterial;
    Kupfer: THREE.MeshStandardMaterial;
    ["Besch.Überschrift"]: THREE.MeshStandardMaterial;
    ["Kabel-Schwarz"]: THREE.MeshStandardMaterial;
    ["Kabel-Metal"]: THREE.MeshStandardMaterial;
    Black: THREE.MeshStandardMaterial;
    Knop: THREE.MeshStandardMaterial;
    ["Gold.002"]: THREE.MeshStandardMaterial;
    LED_Grün: THREE.MeshStandardMaterial;
    LED_Rot: THREE.MeshStandardMaterial;
    Stecker_Schwarz: THREE.MeshStandardMaterial;
    ["Steel_Gebürsted.004"]: THREE.MeshStandardMaterial;
    Schwarz_01: THREE.MeshStandardMaterial;
    ["Gold.Steel.002"]: THREE.MeshStandardMaterial;
    Screen: THREE.MeshStandardMaterial;
    Platine: THREE.MeshStandardMaterial;
    Glas: THREE.MeshPhysicalMaterial;
    ["Car chrome"]: THREE.MeshStandardMaterial;
    ["Gray black pastic"]: THREE.MeshStandardMaterial;
    ["Gold.006"]: THREE.MeshStandardMaterial;
  };
};

const Scene = () => {
  const { nodes, materials } = useGLTF(
    "/models/PortfolioScene.glb"
  ) as GLTFResult;

  const videoTexture = useVideoTexture("/textures/computerScreen.mp4");

  return (
    <group dispose={null}>
      {/* Bench */}
      <group scale={[0.145, 0.01, 0.92]}>
        <mesh
          geometry={nodes.Bench_1.geometry}
          material={materials.Arbetshylla}
        />
        <mesh
          geometry={nodes.Bench_2.geometry}
          material={materials["Arbetsbänk Skiva"]}
        />
        <mesh
          geometry={nodes.Bench_3.geometry}
          material={materials["Leg.001"]}
        />
        <mesh
          geometry={nodes.Bench_4.geometry}
          material={materials["Mat 01"]}
        />
      </group>

      {/* USB */}
      <group>
        {/* USB Cable */}
        <mesh
          geometry={nodes.USB_Cable.geometry}
          material={materials["black.004"]}
        />

        {/* USB Heads */}
        <group>
          <mesh
            geometry={nodes.USB_Heads_1.geometry}
            material={materials["black grain.004"]}
          />
          <mesh
            geometry={nodes.USB_Heads_2.geometry}
            material={materials["black.004"]}
          />
          <mesh
            geometry={nodes.USB_Heads_3.geometry}
            material={materials["metal_02.005"]}
          />
        </group>

        {/* Probe Cable */}
        <mesh
          geometry={nodes.Probe_Cable.geometry}
          material={materials["Kabel-Schwarz"]}
        />
      </group>

      {/* Computer */}
      <group>
        {/* <mesh
          geometry={nodes.Computer_1.geometry}
          material={materials["Opaque(244,244,244)"]}
        /> */}
        <mesh geometry={nodes.Computer_2.geometry} rotation={[0, 0, 0]} />
        <Plane rotation={[-Math.PI / 5, -Math.PI / 5, -Math.PI / 4.4]}>
          <meshBasicMaterial map={videoTexture} toneMapped={false} />
        </Plane>
        {/* <mesh
          geometry={nodes.Computer_3.geometry}
          material={materials["Opaque(5,5,5)"]}
        /> */}
        {/* <mesh
          geometry={nodes.Computer_4.geometry}
          material={materials["Opaque(190,188,186)"]}
        /> */}
        {/* <mesh
          geometry={nodes.Computer_5.geometry}
          material={materials["Opaque(128,128,128)"]}
        /> */}
        {/* <mesh
          geometry={nodes.Computer_6.geometry}
          material={materials["Opaque(191,191,191)"]}
        /> */}
        {/* <mesh
          geometry={nodes.Computer_7.geometry}
          material={materials["Opaque(63,63,63)"]}
        /> */}
        {/* <mesh
          geometry={nodes.Computer_8.geometry}
          material={materials["Opaque(173,173,173)"]}
        /> */}
      </group>

      {/* PCB */}
      <group>
        <mesh
          geometry={nodes.PCB_Model_1.geometry}
          material={materials["Opaque(204,204,204)"]}
        />
        <mesh
          geometry={nodes.PCB_Model_2.geometry}
          material={materials["Opaque(219,188,126)"]}
        />
        <mesh
          geometry={nodes.PCB_Model_3.geometry}
          material={materials["Opaque(250,235,214)"]}
        />
        <mesh
          geometry={nodes.PCB_Model_4.geometry}
          material={materials["Opaque(65,195,130)"]}
        />
        <mesh
          geometry={nodes.PCB_Model_5.geometry}
          material={materials["Opaque(51,153,102)"]}
        />
        <mesh
          geometry={nodes.PCB_Model_6.geometry}
          material={materials["Opaque(210,209,199)"]}
        />
        <mesh
          geometry={nodes.PCB_Model_7.geometry}
          material={materials["Opaque(97,69,55)"]}
        />
        <mesh
          geometry={nodes.PCB_Model_8.geometry}
          material={materials["Opaque(228,227,207)"]}
        />
        <mesh
          geometry={nodes.PCB_Model_9.geometry}
          material={materials["Opaque(21,22,24)"]}
        />
        <mesh
          geometry={nodes.PCB_Model_10.geometry}
          material={materials["Opaque(87,173,113)"]}
        />
        <mesh
          geometry={nodes.PCB_Model_11.geometry}
          material={materials["Opaque(70,70,70)"]}
        />
        <mesh
          geometry={nodes.PCB_Model_12.geometry}
          material={materials["Opaque(38,37,37)"]}
        />
        <mesh
          geometry={nodes.PCB_Model_13.geometry}
          material={materials["Opaque(255,255,255)"]}
        />
        <mesh
          geometry={nodes.PCB_Model_14.geometry}
          material={materials["Opaque(247,224,153)"]}
        />
        <mesh
          geometry={nodes.PCB_Model_15.geometry}
          material={materials["Opaque(255,245,209)"]}
        />
        <mesh
          geometry={nodes.PCB_Model_16.geometry}
          material={materials["Opaque(150,150,150)"]}
        />
        <mesh
          geometry={nodes.PCB_Model_17.geometry}
          material={materials["Opaque(50,50,50)"]}
        />
        <mesh
          geometry={nodes.PCB_Model_18.geometry}
          material={materials["Opaque(185,185,185)"]}
        />
        <mesh
          geometry={nodes.PCB_Model_19.geometry}
          material={materials["Opaque(37,36,36)"]}
        />
        <mesh
          geometry={nodes.PCB_Model_20.geometry}
          material={materials["Opaque(176,169,152)"]}
        />
        <mesh
          geometry={nodes.PCB_Model_21.geometry}
          material={materials["Opaque(41,41,41)"]}
        />
      </group>

      {/* Oscilloscope */}
      <group>
        <mesh
          geometry={nodes.Oscilloscope_1.geometry}
          material={materials["Plastic structured in gray"]}
        />
        <mesh
          geometry={nodes.Oscilloscope_2.geometry}
          material={materials["Plastic structured in gray"]}
        />
        <mesh
          geometry={nodes.Oscilloscope_3.geometry}
          material={materials["Menue-buton-M"]}
        />
        <mesh
          geometry={nodes.Oscilloscope_4.geometry}
          material={materials["Menue-buton.Color"]}
        />
        <mesh
          geometry={nodes.Oscilloscope_5.geometry}
          material={materials["Buton-Blau"]}
        />
        <mesh
          geometry={nodes.Oscilloscope_6.geometry}
          material={materials["Besch.Tasten-hintergrund"]}
        />
        <mesh
          geometry={nodes.Oscilloscope_7.geometry}
          material={materials.Grau}
        />
        <mesh
          geometry={nodes.Oscilloscope_8.geometry}
          material={materials["LED-Grün"]}
        />
        <mesh
          geometry={nodes.Oscilloscope_9.geometry}
          material={materials["RUN-STOP_txt"]}
        />
        <mesh
          geometry={nodes.Oscilloscope_10.geometry}
          material={materials["Menue-buton-M"]}
        />
        <mesh
          geometry={nodes.Oscilloscope_11.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Oscilloscope_12.geometry}
          material={materials.Besch}
        />
        <mesh
          geometry={nodes.Oscilloscope_13.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Oscilloscope_14.geometry}
          material={materials["Metal-Farbe-01"]}
        />
        <mesh
          geometry={nodes.Oscilloscope_15.geometry}
          material={materials.Metal}
        />
        <mesh
          geometry={nodes.Oscilloscope_16.geometry}
          material={materials.Isolator}
        />
        <mesh
          geometry={nodes.Oscilloscope_17.geometry}
          material={materials.Kupfer}
        />
        <mesh
          geometry={nodes.Oscilloscope_18.geometry}
          material={materials["Besch.Überschrift"]}
        />
        <mesh
          geometry={nodes.Oscilloscope_19.geometry}
          material={materials.Metal}
        />
        <mesh
          geometry={nodes.Oscilloscope_20.geometry}
          material={materials["Kabel-Schwarz"]}
        />
        <mesh
          geometry={nodes.Oscilloscope_21.geometry}
          material={materials["Kabel-Metal"]}
        />
        <mesh
          geometry={nodes.Oscilloscope_22.geometry}
          material={materials.Black}
        />
        <mesh
          geometry={nodes.Oscilloscope_23.geometry}
          material={materials.Knop}
        />
        <mesh
          geometry={nodes.Oscilloscope_24.geometry}
          material={materials["Gold.002"]}
        />
        <mesh
          geometry={nodes.Oscilloscope_25.geometry}
          material={materials.LED_Grün}
        />
        <mesh
          geometry={nodes.Oscilloscope_26.geometry}
          material={materials.LED_Rot}
        />
        <mesh
          geometry={nodes.Oscilloscope_27.geometry}
          material={materials.Stecker_Schwarz}
        />
        <mesh
          geometry={nodes.Oscilloscope_28.geometry}
          material={materials["Steel_Gebürsted.004"]}
        />
        <mesh
          geometry={nodes.Oscilloscope_29.geometry}
          material={materials.Schwarz_01}
        />
        <mesh
          geometry={nodes.Oscilloscope_30.geometry}
          material={materials["Gold.Steel.002"]}
        />
        <mesh
          geometry={nodes.Oscilloscope_31.geometry}
          material={materials["black.004"]}
        />
        <mesh
          geometry={nodes.Oscilloscope_32.geometry}
          material={materials.Screen}
        />
        <mesh
          geometry={nodes.Oscilloscope_33.geometry}
          material={materials.Platine}
        />
        <mesh
          geometry={nodes.Oscilloscope_34.geometry}
          material={materials.Glas}
        />
        <mesh
          geometry={nodes.Oscilloscope_35.geometry}
          material={materials["Car chrome"]}
        />
        <mesh
          geometry={nodes.Oscilloscope_36.geometry}
          material={materials["black.004"]}
        />
        <mesh
          geometry={nodes.Oscilloscope_37.geometry}
          material={materials["black.004"]}
        />
        <mesh
          geometry={nodes.Oscilloscope_38.geometry}
          material={materials["Gold.002"]}
        />
        <mesh
          geometry={nodes.Oscilloscope_39.geometry}
          material={materials["Car chrome"]}
        />
        <mesh
          geometry={nodes.Oscilloscope_40.geometry}
          material={materials["Gray black pastic"]}
        />
        <mesh
          geometry={nodes.Oscilloscope_41.geometry}
          material={materials.Metal}
        />
        <mesh
          geometry={nodes.Oscilloscope_42.geometry}
          material={materials.Isolator}
        />
        <mesh
          geometry={nodes.Oscilloscope_43.geometry}
          material={materials["Kabel-Schwarz"]}
        />
        <mesh
          geometry={nodes.Oscilloscope_44.geometry}
          material={materials["Gold.006"]}
        />
        <mesh
          geometry={nodes.Oscilloscope_45.geometry}
          material={materials.Metal}
        />
        <mesh
          geometry={nodes.Oscilloscope_46.geometry}
          material={materials.Isolator}
        />
        <mesh
          geometry={nodes.Oscilloscope_47.geometry}
          material={materials["Kabel-Schwarz"]}
        />
        <mesh
          geometry={nodes.Oscilloscope_48.geometry}
          material={materials["Gold.006"]}
        />
        <mesh
          geometry={nodes.Oscilloscope_49.geometry}
          material={materials.Metal}
        />
        <mesh
          geometry={nodes.Oscilloscope_50.geometry}
          material={materials.Isolator}
        />
        <mesh
          geometry={nodes.Oscilloscope_51.geometry}
          material={materials["Kabel-Schwarz"]}
        />
        <mesh
          geometry={nodes.Oscilloscope_52.geometry}
          material={materials["Gold.006"]}
        />
        <mesh
          geometry={nodes.Oscilloscope_53.geometry}
          material={materials.Metal}
        />
        <mesh
          geometry={nodes.Oscilloscope_54.geometry}
          material={materials.Isolator}
        />
        <mesh
          geometry={nodes.Oscilloscope_55.geometry}
          material={materials["Kabel-Schwarz"]}
        />
        <mesh
          geometry={nodes.Oscilloscope_56.geometry}
          material={materials["Gold.006"]}
        />
      </group>
    </group>
  );
};

useGLTF.preload("/models/PortfolioScene.glb");

export default Scene;
